version: 0.0
os: linux
files:
   - source: /
     destination: /opt/codedeploy-agent
permissions:
   - object: /opt/codedeploy-agent
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installflask.sh
      runas: root
    - location: scripts/startflask.sh
      runas: root
   AfterInstall:
    - location: scripts/restartflask.sh
      runas: root
