version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/
permissions:
  - object: /home/ubuntu/
    owner: root
    group: root
    mode: 777
hooks:
   BeforeInstall:
    - location: scripts/installflask.sh
      runas: root
    - location: scripts/startflask.sh
      runas: root
   AfterInstall:
    - location: scripts/restartflask.sh
      runas: root
